Add video-miner to ecosystem
livepeer/org pull request #190
Opened 2023-03-01 09:07 UTC by eliteprox

Adds Video-Miner to the Livepeer ecosystem page.
This PR will close #189

2023-03-01 18:46 UTC, adamsoffer requested changes
Thanks for the PR @eliteprox. Can you please move this into the `community` directory?

https://github.com/livepeer/org/tree/main/content/community

2023-03-01 19:08 UTC, eliteprox commented
> Thanks for the PR @eliteprox. Can you please move this into the `community` directory?
> 
> https://github.com/livepeer/org/tree/main/content/community

Thanks, I have moved the file now

2023-03-02 20:28 UTC, eliteprox commented on content/community/video_miner.md
> +  https://user-images.githubusercontent.com/16746274/222543634-6ffa38ad-d692-4dee-b800-1d969ad6dec7.png
Please upload the attached logo to cloudinary and update the image url.
![videominer_logo_ecosystem2-01-02](https://user-images.githubusercontent.com/16746274/222544353-2bf8b79d-e9e8-4102-854a-83827149820e.png)

2023-03-14 15:11 UTC, AuthorityNull commented
Hi @adamsoffer, can we get an update on this? Thanks.

2023-03-14 15:20 UTC, adamsoffer approved these changes

2023-03-14 15:39 UTC, eliteprox commented
The image still needs to be uploaded to cloudinary. Core team will handle that, correct?

2023-03-14 15:42 UTC, merged